apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: confluentplatforms.kafka.pm.bet
spec:
  group: kafka.pm.bet
  names:
    kind: ConfluentPlatform
    plural: confluentplatforms
    singular: confluentplatform
    shortNames:
    - cp
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              version:
                type: string
                pattern: '^(\d+).(\d+).(\d+)$'
                default: "5.3.1"
          status:
            type: object
            properties:
              version:
                type: string
              labelSelector:
                type: string
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Zookeeper
      type: string
      jsonPath: .spec.zookeeper.enabled
    - name: Kafka
      type: boolean
      jsonPath: .spec.kafka.enabled
    - name: Schema Registry
      type: boolean
      jsonPath: .spec.schemaRegistry.enabled
    - name: Kafka connect
      type: boolean
      jsonPath: .spec.kafkaConnect.enabled
    - name: KSQLDB Server
      type: boolean
      jsonPath: .spec.ksqldbServer.enabled
    - name: Kafka Rest
      type: boolean
      jsonPath: .spec.kafkaRest.enabled
    - name: Control Center
      type: boolean
      jsonPath: .spec.controlCenter.enabled
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
