---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mirrormakers.kafka.pm.bet
spec:
  group: kafka.pm.bet
  names:
    kind: MirrorMaker
    listKind: MirrorMakerList
    plural: mirrormakers
    singular: mirrormaker
    shortNames:
    - mm
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  additionalPrinterColumns:
  - name: Partitions
    type: integer
    description: Number of topic partitions
    JSONPath: .spec.partitions
  - name: Replication Factor
    type: integer
    description:  Replication factor of topic
    JSONPath: .spec.replicationFactor
  - name: Retention ms
    type: integer
    JSONPath: .spec.options.retentionMs
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  versions:
  - name: v1beta1
    served: true
    storage: true
